### PR TITLE
Update ReactiveSwift

### PR DESCRIPTION
**Pull request by stephencelis**
Takes us into 2.0 territory.

### CODE REVIEW

**Comment by justinswart** [comment]
@stephencelis lemme know if you agree with the fix in that last commit - essentially just bringing over the changes that they made in https://github.com/ReactiveCocoa/ReactiveSwift/pull/228

**Comment by wongzigii** [comment]
Hello, everyone, is there any reason why we are not merging this pull request ?

**Comment by wongzigii** [comment]
cc/ @justinswart @stephencelis

**Comment by justinswart** [comment]
@wongzigii hi we've been a bit busy with some other stuff but we'll get back to this soon 🙂. It wasn't merged yet because we had to make additional changes in the main app's codebase in order to do so.

**Pull request merged**
